<h1>Introduction to NumPy</h1>

<h2>What is NumPy?</h2>

NumPy stands for Numerical Python.

It is a Python library mainly used for working with numbers, arrays, mathematical calculations, and data. It provides a powerful object called ndarray (N-dimensional array) that stores data in a compact and optimized format.

In [3]:
#Normal python:

numbers = [10,20,30,40]

#Numpy

import numpy as np

numbers = np.array([10,20,30,40])
print(numbers)

[10 20 30 40]


<h3>AI/ML Usage</h3>

Almost every Machine Learning dataset is converted into NumPy arrays before training a model because mathematical calculations are much faster.

<h2>Why NumPy?</h2>


Python lists can store numbers, but NumPy arrays are specifically designed for numerical operations.

NumPy provides:

<ul><li>Faster numerical calculations</li>
<li>Mathematical functions</li>
<li>Multidimensional arrays</li>
<li>Matrix operations</li>
<li>Memory-efficient numerical storage</li>
<li>Easy operations on entire arrays</li></ul>

In [6]:
import numpy as np

python_list = [10,20,30,40]

Numpy_array = np.array([10,20,30,40])

print(type(python_list))
print(type(Numpy_array))

<class 'list'>
<class 'numpy.ndarray'>


<h3>AI/ML Usage</h3>

Machine learning algorithms perform thousands of mathematical operations.

Using NumPy makes these operations much faster than Python lists.

<h2>NumPy Arrays (ndarray)</h2>

The main object in NumPy is called ndarray (N-dimensional array).

It stores data of the same data type in one place.

Unlike Python lists, NumPy arrays are homogeneous.

In [9]:
import numpy as np

arr = np.array([5,10,15,20])
print(arr)

[ 5 10 15 20]


<h3>AI/ML Usage</h3>

Dataset features are usually stored as NumPy arrays before training models.

Example:

Age

Salary

Experience

which becomes,

In [11]:
data = np.array([
    [25,40000,2],
    [30,50000,5],
    [35,60000,8]
])

print(data)

[[   25 40000     2]
 [   30 50000     5]
 [   35 60000     8]]


<h2>Creating Arrays</h2>

There are several ways to create NumPy arrays.

Common one is:

In [12]:
import numpy as np

arr = np.array([1,2,3,4])
print(arr)

[1 2 3 4]


NumPy also provides functions such as:

np.zeros()<br>
np.ones()<br>
np.arange()<br>

In [13]:
import numpy as np

a = np.array([10, 20, 30])
b = np.zeros(5)
c = np.ones(5)
d = np.arange(5)

print(a)
print(b)
print(c)
print(d)

[10 20 30]
[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]
[0 1 2 3 4]


<h3>AI/ML use</h3>

This can be useful when working with algorithms that require an initial set of weights or values.

<h2>Dimensions</h2>

Dimension tells us how many levels/axes an array has.

In [ ]:
[1,2,3,4] - 1D
[[1,2],[3,4] - 2D
[[[1]]] - 3D


In [20]:
import numpy as np

a = np.array([1,2,3,4])

b = np.array([[1,2],[3,4]])

c = np.array([[[1],[2]],[[3],[4]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)

1
2
3


__.ndim?__

How many dimensions does this array have?

<h3>AI/ML use</h3>

Dimensions are important because datasets can have different structures.

1D - [feature values]

2D - [rows × features]

3D - images/sequences/other structured data

<h2>Shape</h2>

Shape tells us how many elements exist along each dimension.

In [25]:
arr = np.array([[1,2,3],
              [4,5,6]])
print(arr.shape)

(2, 3)


Meaning

2 rows<br>
3 columns

Shape = rows × columns for a 2D array.

<h3>AI/ML use</h3>

Before training a model, checking the dataset shape ensures the data is in the correct format.

(1000, 5)

1000 - observations/rows<br>
5    - features/columns

<h2>Size</h2>


Size tells us the total number of elements in an array.

In [28]:
arr = np.array([[1,2,3],
                [4,5,6]])

print(arr.size)

6


2 rows × 3 colums = 6 elements

<h3>AI/ML use</h3>

It can help you understand the amount of numerical data you're working with and check whether an array has the expected number of values.

<h2>Data Types</h2>
A NumPy array stores values with a particular data type.

Common NumPy data types:

int - whole numbers<br>
float - decimal numbers<br>
bool - True / False<br>
str - text

In [30]:
arr = np.array([10,20,30])

print(arr.dtype)

int64


__dtype__ tells you what type of data the NumPy array is storing.

In [32]:
#Changing datatype

arr = arr.astype(float)

print(arr)
print(arr.dtype)

[10. 20. 30.]
float64


<h3>AI/ML Usage</h3>

Deep learning often uses float32 because it consumes less memory and trains faster.

<h2>Indexing</h2>
Indexing means accessing a particular element from an array.

In [33]:
arr = np.array([10,20,30,40])

print(arr[0])
print(arr[2])

10
30


<h3>2D</h3>

In [35]:
arr = np.array([[1,2],[3,4]])
print(arr[1,0])

3


<h3>AI/ML Usage</h3>

Selecting a specific feature column.

<h2>Slicing</h2>
Slicing means taking a portion of an array.

In [36]:
arr = np.array([10,20,30,40,50])

print(arr[1:4])

[20 30 40]


<h3>2D</h3>

In [44]:
arr = np.array([[10,20,30],[40,50,60]])

print(arr[1][0:3])

[40 50 60]


<h3>AI/ML Usage</h3>

Selecting input features.
    
Selecting target column.

<h2>Reshaping</h2>

Reshaping changes the structure of an array without changing its data.

In [49]:
arr = np.arange(12)

new = arr.reshape(3,4)
print(new)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


<h3>AI/ML Usage</h3>

Images are reshaped before training CNNs.

<h2>Flatten</h2>
Flatten converts a multidimensional array into a one-dimensional array.

In [55]:
arr = np.array([[1,2],[3,4]])

flat = arr.flatten()
print(flat)
print(arr.shape)
print(flat.shape)

[1 2 3 4]
(2, 2)
(4,)


<h2>AI/ML Usage</h2>

Flattening is commonly used when converting multidimensional data into a single vector.

Example

28 × 28

pixels.

Flattening converts it into:

784

values:

28 × 28 = 784

This can be useful when feeding image data into certain traditional ML models

<h2>Copy vs View</h2>

<h4>Copy</h4>

Creates a new independent array.

Changing the copy does not change the original.

In [58]:
a = np.array([10, 20, 30])

b = a.copy()

b[0] = 100
print(a)
print(b)

[10 20 30]
[100  20  30]


<h4>View</h4>

Creates another way of looking at the same underlying data.

Changing the view can change the original.

In [59]:
a = np.array([10,20,30])

b = a.view()

b[0] = 100

print(a)
print(b)

[100  20  30]
[100  20  30]


<h2>AI/ML Usage</h2>

Copies protect original datasets while preprocessing.

Views save memory for large datasets.

<h2>Broadcasting</h2>
Broadcasting allows NumPy to perform operations between arrays of different shapes when their shapes are compatible.

In [67]:
import numpy as np

salary = np.array([20000,22000,30000])

new_salary = salary + 5000

print(new_salary)

matrix = np.array([[1,2,3],
                   [4,5,6]])

vector = np.array([10,20,30])

print(matrix + vector)

[25000 27000 35000]
[[11 22 33]
 [14 25 36]]


<h3>AI/ML Usage</h3>

Feature scaling

New Value = Original Value - Mean

Mean values are broadcast across every row.

<h2>Array Operations</h2>

Array operations mean performing mathematical operations directly on NumPy arrays.

NumPy can perform an operation on all elements of an array at once.

In [68]:
a = np.array([1,2,3])

b = np.array([4,5,6])

print(a+b)

print(a-b)

print(a*b)

print(a/b)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


In [71]:
print(a > 2)
print(a[a > 2])

[False False  True]
[3]


Aggregation Operations

NumPy also provides functions to summarize an array.

In [72]:
print(np.sum(a))

print(np.mean(a))

print(np.max(a))

print(np.min(a))

6
2.0
3
1


<h3>AI/ML Usage</h3>

Used while calculating:

Mean<br>
Standard deviation<br>
Euclidean distance<br>
Loss functions<br>
Accuracy metrics

<h2>Universal Functions (ufuncs)</h2>

Universal functions, commonly called ufuncs, are NumPy functions that operate on array elements efficiently.

A ufunc applies a mathematical operation to each element of a NumPy array.

In [73]:
#square root
arr = np.array([1,4,9,16])

print(np.sqrt(arr))

[1. 2. 3. 4.]


In [75]:
arr = np.array([1,2,3])

print(np.square(arr))

#Exponential – np.exp()

print(np.exp(arr))

print(np.log(arr))

print(np.sin(arr))

print(np.cos(arr))

#Absolute Value – np.abs()

print(np.abs([-2,-5,6]))

[1 4 9]
[ 2.71828183  7.3890561  20.08553692]
[0.         0.69314718 1.09861229]
[0.84147098 0.90929743 0.14112001]
[ 0.54030231 -0.41614684 -0.9899925 ]
[2 5 6]
