<h1>NumPy Random Module</h1>

In [2]:
import numpy as np

<h2>Random Numbers</h2>

Random numbers are numbers generated without following a fixed pattern.

NumPy provides the random module to generate random values quickly.

The generated numbers are usually floating-point numbers between 0 and 1.

Example

Imagine you're building an online gaming application where a treasure chest gives a random reward every time a player opens it. The reward should be unpredictable.

In [2]:
reward = np.random.rand()
print(reward)

0.7840821366408214


If the number is:

Less than 0.3 - Bronze Reward<br>
Between 0.3 and 0.7 - Silver Reward<br>
Above 0.7 - Gold Reward

<h3>AI/ML Usage</h3>

Random numbers are used to initialize neural network weights and simulate random events during model training.

<h2>Random Seed</h2>

A Random Seed fixes the sequence of random numbers.

Without setting a seed, different random numbers are generated every time the program runs.

Using a seed ensures reproducible results, which is very important in Machine Learning experiments.

<h3>Example</h3>

Two data scientists are working on the same customer churn model. They want to get exactly the same train-test split so they can compare their results fairly.

In [5]:
np.random.seed(42)
print(np.random.randint(1,100,5))

[52 93 15 72 61]


<h3>AI/ML Usage</h3>

Random seeds make machine learning experiments reproducible.

<h2>Random Integers</h2>

Generates random integer values within a specified range.

<h3>Example</h3>
    
A teacher wants to generate 10 random roll numbers for selecting students to answer questions.

In [5]:
roll_numbers = np.random.randint(1,51,size=10)
print(roll_numbers)

[21 39 19 23 11 11 24 36 40 24]


<h3>AI/ML Usage</h3>

Used for generating sample datasets, customer IDs, labels, and testing algorithms.

<h2>Random Choice</h2>

Selects random values from a given list or array.

It can also generate random values according to specified probabilities.

<h3>Example</h3>

An e-commerce company wants to randomly choose one customer for a free gift.

In [6]:
customers = ["Arjun","Ragul","Prakash","Jothi","Magesh"]

winner = np.random.choice(customers)
print(winner)

Magesh


<h3>AI/ML Usage</h3>

Used in bootstrap sampling, mini-batch selection, and recommendation systems.

<h2>Shuffle</h2>

Shuffle randomly rearranges the elements of an array.

It changes the original array.

Example
Suppose exam questions are arranged in order. Before giving the paper to students, the questions are shuffled.

In [7]:
questions = np.array([1,2,3,4,5,6])

np.random.shuffle(questions)
print(questions)

[6 1 4 5 3 2]


<h3>AI/ML Usage</h3>

Training datasets are shuffled before every training epoch to prevent the model from learning patterns based on data order.

<h2>Permutation</h2>

Permutation also rearranges the elements randomly.

Unlike shuffle(), it does not modify the original array. Instead, it returns a new shuffled array.

Example

A company has employee IDs stored in a list. The HR team wants a random order for assigning interview slots but doesn't want to change the original list.

In [12]:
employees = np.array([101,102,103,104,105])

random_order = np.random.permutation(employees)

print("Original:",employees)
print("Interview Order:",random_order)

Original: [101 102 103 104 105]
Interview Order: [103 104 101 105 102]


<h3>AI/ML Usage</h3>

Used for train-test splitting and randomized experiments while preserving the original dataset.

<h2>Random Distributions</h2>

A Random Distribution generates numbers that follow a specific statistical pattern instead of being completely random.

Some commonly used distributions are:

<ul><li>Uniform Distribution</li>
<li>Normal Distribution</li>
<li>Binomial Distribution</li></ul>
These are widely used in AI, ML, simulations, and statistical modeling.

<h3>Uniform Distribution</h3>
Every value has an equal chance of being selected.

Example
    
Suppose an online shopping website wants to generate a random discount between 10% and 20%, where every value has an equal chance.

In [9]:
discount = np.random.uniform(10,20,5)
print(discount)

[10.56411579 17.21998772 19.38552709 10.00778766 19.92211559]


<h3>AI/ML Usage</h3>

Used in random simulations and weight initialization.

<h3>Normal Distribution</h3>

Generates values that follow a bell-shaped curve.

Most values are close to the mean.

Example
    
The heights of students in a school usually follow a normal distribution.

In [10]:
import numpy as np

heights = np.random.normal(
    loc=165,
    scale=7,
    size=10
)

print(heights)

[175.23664684 175.77100477 147.92625929 169.22408858 163.24269222
 163.85293018 154.66569215 175.40886671 164.82881376 167.48885922]


Most students are close to 165 cm, while very short and very tall students are less common.

<h3>AI/ML Usage</h3>

Used for generating realistic datasets, adding noise, and initializing neural network parameters.

<h3>Binomial Distribution</h3>

Produces the number of successes in a fixed number of independent trials.

Example

A cricket player plays 10 balls. Each ball has a 60% chance of scoring a run. We want to know how many successful scoring shots occur.

In [11]:
import numpy as np

runs = np.random.binomial(
    n=10,
    p=0.6,
    size=5
)

print(runs)

[4 5 6 9 4]


Each value represents the number of successful scoring shots out of 10 balls.

<h3>AI/ML Usage</h3>

Used in binary classification, success/failure experiments, A/B testing, and probability modeling.